"""Fail-closed launch orchestration.

The state machine deliberately owns policy.  Adapters own I/O, which keeps
the dangerous path entirely fake-testable.
"""
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
import json
from pathlib import Path
from typing import Any, Callable, Protocol, runtime_checkable
import uuid
import re

from grim_dawn_sync.config import SyncConfig
from grim_dawn_sync.errors import EXIT_CONFLICT, EXIT_RECOVERY_REQUIRED, EXIT_VALIDATION, SyncError
from grim_dawn_sync.git_vault import GitVault
from grim_dawn_sync.launcher import DPYesLauncher
from grim_dawn_sync.manifest import _reject_unsafe, build_manifest, stable_manifest
from grim_dawn_sync.session_lock import acquire_lock, release_lock
from grim_dawn_sync.snapshot import _copy_verified, _manifest, apply_restore, archive_before_restore, plan_restore
from grim_dawn_sync.state import SyncState, load_state, save_state
from grim_dawn_sync.validation import validate_players


class WorkflowState(str, Enum):
    PREFLIGHT="PREFLIGHT"; FETCH_REMOTE="FETCH_REMOTE"; RECONCILE="RECONCILE"; ACQUIRE_LOCK="ACQUIRE_LOCK"
    ARCHIVE_BEFORE_RESTORE="ARCHIVE_BEFORE_RESTORE"; APPLY_REMOTE_SAVE="APPLY_REMOTE_SAVE"; START_DPYES="START_DPYES"
    WAIT_GAME_START="WAIT_GAME_START"; WAIT_GAME_EXIT="WAIT_GAME_EXIT"; WAIT_SAVE_STABLE="WAIT_SAVE_STABLE"
    VALIDATE_SAVE="VALIDATE_SAVE"; ARCHIVE_AFTER_GAME="ARCHIVE_AFTER_GAME"; UPDATE_VAULT="UPDATE_VAULT"
    COMMIT="COMMIT"; PUSH="PUSH"; RELEASE_LOCK="RELEASE_LOCK"; COMPLETE="COMPLETE"


class JsonlLog:
    """Best-effort privacy-safe audit log.  Logging must never mask recovery."""
    def __init__(self, path: Path, *, machine_id: str | None = None) -> None:
        self.path, self.machine_id = Path(path), machine_id
    def write(self, state: WorkflowState, event: str, code: str | None = None, *, session_id: str | None = None, last_successful_state: WorkflowState | None = None, safe_oid: str | None = None, safe_root_hash: str | None = None, archive_root: str | None = None, quarantine_root: str | None = None, archive_id: str | None = None, quarantine_id: str | None = None) -> None:
        # Values are allow-listed identifiers only; callers never pass paths or exception text.
        row: dict[str, str] = {"schema_version":"1.0.0", "timestamp_utc":datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00","Z"), "state":state.value, "event":event}
        if self.machine_id and re.fullmatch(r"[A-Za-z0-9._-]{1,128}",self.machine_id): row["machine_id"] = self.machine_id
        if session_id and re.fullmatch(r"[A-Za-z0-9._-]{1,128}",session_id): row["session_id"] = session_id
        if last_successful_state: row["last_successful_state"] = last_successful_state.value
        if safe_oid and re.fullmatch(r"[0-9a-f]{40}(?:[0-9a-f]{24})?",safe_oid): row["safe_oid"] = safe_oid
        if safe_root_hash and re.fullmatch(r"[0-9a-f]{64}",safe_root_hash): row["safe_root_hash"] = safe_root_hash
        if archive_root and re.fullmatch(r"[0-9a-f]{64}",archive_root): row["archive_root"] = archive_root
        if quarantine_root and re.fullmatch(r"[0-9a-f]{64}",quarantine_root): row["quarantine_root"] = quarantine_root
        # These are basename identifiers generated by us, never save-relative paths.
        if archive_id and re.fullmatch(r"save-[0-9TZ-]+-[0-9a-f]{16}-[0-9a-f]{32}", archive_id): row["archive_id"] = archive_id
        if quarantine_id and re.fullmatch(r"save-[0-9TZ-]+-[0-9a-f]{16}-[0-9a-f]{32}", quarantine_id): row["quarantine_id"] = quarantine_id
        if code:
            row["code"] = code
            row["next_command"] = "grim-dawn-sync status" if code in {"vault_not_reconciled","remote_main_missing","bootstrap_required"} else "grim-dawn-sync recover"
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self.path.open("a", encoding="utf-8", newline="\n") as out: out.write(json.dumps(row, sort_keys=True, separators=(",",":"))+"\n")


@runtime_checkable
class WorkflowAdapters(Protocol):
    """The complete launch boundary.  It is checked before any I/O occurs."""
    def preflight(self) -> None: ...
    def state(self) -> SyncState: ...
    def live_manifest(self) -> dict: ...
    def remote_manifest(self, base: str, session: str) -> dict: ...
    def fetch_and_reconcile(self) -> Any: ...
    def remote_oid(self) -> str | None: ...
    def acquire(self, base: str) -> Any: ...
    def prepare_remote_restore(self, base: str, session: str) -> Any: ...
    def archive_before_restore(self, plan: Any) -> Any: ...
    def apply_remote_save(self, plan: Any) -> Any: ...
    def launch(self, hook: Callable[[str], None]) -> Any: ...
    def wait_save_stable(self) -> dict: ...
    def validate(self, manifest: dict, baseline: dict | None) -> dict: ...
    def archive_after_game(self, manifest: dict) -> str: ...
    def rescue_raw(self, manifest: dict | None) -> str: ...
    def quarantine(self, manifest: dict) -> str: ...
    def snapshot(self, session: str, manifest: dict, hook: Callable[[str], None]) -> str: ...
    def mark_committed(self, lock: Any, oid: str, root_hash: str) -> None: ...
    def push(self, oid: str) -> str: ...
    def release(self, lock: Any, oid: str, manifest: dict) -> None: ...


class DomainAdapters:
    def __init__(self, config: SyncConfig, local_root: Path) -> None:
        self.config, self.local_root = config, Path(local_root); self.vault = GitVault(config.vault_repo, remote=config.remote, branch=config.branch)
        self.last_archive_destination: str | None = None
        self.last_quarantine_destination: str | None = None
        self.last_archive_root: str | None = None
        self.last_quarantine_root: str | None = None
    @property
    def state_path(self) -> Path: return self.local_root / "state.json"
    def preflight(self) -> None:
        self.vault.preflight()
        # Refuse before lock acquisition if a configured process is present or unidentifiable.
        scan=DPYesLauncher(self.config)._scan()
        names={name.casefold() for name in self.config.game_process_names} | {"dpyes.exe"}
        if any(item.name.casefold() in names for item in scan.processes):
            raise SyncError("game_already_running","Configured Grim Dawn process already exists.",5)
    def state(self) -> SyncState: return load_state(self.state_path)
    def live_manifest(self) -> dict: return stable_manifest(self.config.save_root, machine_id=self.config.machine_id, retries=self.config.stable_scan_retries, window_seconds=0)
    def remote_manifest(self, base: str, session: str) -> dict:
        return self.vault.read_manifest(base)
    def fetch_and_reconcile(self): return self.vault.update_fast_forward()
    def remote_oid(self) -> str | None: return self.vault.remote_oid()
    def acquire(self, base: str): return acquire_lock(self.vault,self.config.machine_id,base,state_path=self.state_path)
    def prepare_remote_restore(self, base: str, session: str):
        source=self.local_root/"staging"/session
        self.vault.extract_save(base,source,machine_id=self.config.machine_id,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds)
        return plan_restore(source,self.config.save_root,self.local_root/"archives",self.local_root/"recovery",machine_id=self.config.machine_id,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds,session_id=session)
    def archive_before_restore(self, plan): return archive_before_restore(plan,machine_id=self.config.machine_id,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds)
    def apply_remote_save(self, plan): return apply_restore(plan,self.local_root/"recovery",machine_id=self.config.machine_id,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds)
    def launch(self, hook: Callable[[str],None]): return DPYesLauncher(self.config,state_hook=hook).run()
    def wait_save_stable(self) -> dict: return stable_manifest(self.config.save_root,machine_id=self.config.machine_id,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds)
    def validate(self, manifest: dict, baseline: dict | None = None) -> dict:
        result=validate_players(self.config.save_root,manifest)
        if not result.get("ok"): raise SyncError(result.get("classification","save_invalid"),"Save validation did not permit snapshot.",EXIT_VALIDATION)
        if baseline and (manifest["character_count"] < baseline["character_count"] or manifest["file_count"] < baseline["file_count"] or manifest["total_bytes"] < baseline["total_bytes"]):
            self.quarantine(manifest); raise SyncError("destructive_change","Save became smaller than its launch baseline; it was quarantined.",EXIT_VALIDATION)
        return manifest
    def _unique_destination(self, category: str, manifest: dict) -> Path:
        # mkdir("x") is performed by _copy_verified; UUID avoids every prior run.
        stamp=datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        return self.local_root/category/f"save-{stamp}-{manifest['root_hash'][:16]}-{uuid.uuid4().hex}"
    def _destination_root(self, category: str) -> Path:
        """Create the local archive root without traversing a link/reparse ancestor."""
        root = self.local_root / category
        ancestors = tuple(reversed((root, *root.parents)))
        def inspect_existing() -> None:
            for ancestor in ancestors:
                try:
                    ancestor.lstat()
                except FileNotFoundError:
                    continue
                except OSError as error:
                    raise SyncError("snapshot_root_unavailable", "Local snapshot root could not be inspected.", EXIT_VALIDATION) from error
                _reject_unsafe(ancestor)
                if not ancestor.is_dir():
                    raise SyncError("snapshot_root_unsafe", "Local snapshot root has a non-directory ancestor.", EXIT_VALIDATION)
        # Inspect first: mkdir(parents=True) must never traverse an existing
        # symlink, junction, mount reparse point, or other redirection.
        inspect_existing()
        try:
            root.mkdir(parents=True, exist_ok=True)
        except OSError as error:
            raise SyncError("snapshot_root_unavailable", "Local snapshot root could not be created.", EXIT_VALIDATION) from error
        # Recheck the full chain after creation to detect replacement races.
        inspect_existing()
        return root
    def _new_destination(self, category: str, manifest: dict) -> Path:
        self._destination_root(category)
        # UUID makes a duplicate root hash a new safe archive, never an overwrite.
        return self._unique_destination(category, manifest)
    def quarantine(self, manifest: dict) -> str:
        dest=self._new_destination("quarantine",manifest)
        _copy_verified(self.config.save_root,dest,manifest,self.config.machine_id,self.config.stable_scan_retries,0,validate_players)
        self.last_quarantine_destination = dest.name
        self.last_quarantine_root = manifest["root_hash"]
        return manifest["root_hash"]
    def archive_after_game(self, manifest: dict) -> str:
        dest=self._new_destination("archives",manifest)
        _copy_verified(self.config.save_root,dest,manifest,self.config.machine_id,self.config.stable_scan_retries,0,validate_players)
        self.last_archive_destination = dest.name
        self.last_archive_root = manifest["root_hash"]
        return manifest["root_hash"]
    def rescue_raw(self, manifest: dict | None) -> str:
        """Validation-permissive, local-only copy; tree safety and hash integrity remain strict."""
        raw=manifest or build_manifest(self.config.save_root,machine_id=self.config.machine_id)
        dest=self._new_destination("quarantine",raw)
        _copy_verified(self.config.save_root,dest,raw,self.config.machine_id,1,0,lambda _root, _manifest: {"ok":True})
        self.last_quarantine_destination = dest.name
        self.last_quarantine_root = raw["root_hash"]
        return raw["root_hash"]
    def snapshot(self, session: str, manifest: dict, hook: Callable[[str],None]) -> str:
        # Requiring the already-validated manifest prevents an unbound snapshot.
        return self.vault.snapshot(self.config.save_root,machine_id=self.config.machine_id,session_id=session,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds,expected_manifest=manifest,state_hook=hook)
    def mark_committed(self, lock: object, oid: str, root_hash: str) -> None:
        s=lock.session; save_state(self.state_path,SyncState(last_applied_manifest_root_hash=root_hash,session_id=s.session_id,machine_id=s.machine_id,base_commit=s.base_commit,lock_oid=lock.oid,local_tag=lock.local_tag,phase="committed",local_commit=oid))
    def push(self, oid: str) -> str: return self.vault.push(oid)
    def release(self, lock: object, oid: str, manifest: dict) -> None:
        release_lock(
            self.vault,
            lock,
            oid,
            state_path=self.state_path,
            confirmed_root_hash=manifest["root_hash"],
        )


class LaunchWorkflow:
    _REQUIRED_METHODS = (
        "preflight", "state", "live_manifest", "remote_manifest", "fetch_and_reconcile", "remote_oid", "acquire",
        "prepare_remote_restore", "archive_before_restore", "apply_remote_save", "launch", "wait_save_stable", "validate",
        "archive_after_game", "rescue_raw", "quarantine", "snapshot", "mark_committed", "push", "release",
    )
    def __init__(self,config:SyncConfig,local_root:Path,*,adapters:WorkflowAdapters|None=None,logger:JsonlLog|None=None)->None:
        self.config,self.local_root=config,Path(local_root); self.adapters=DomainAdapters(config,self.local_root) if adapters is None else adapters
        self.logger=JsonlLog(self.local_root/"logs"/"launch.jsonl",machine_id=config.machine_id) if logger is None else logger; self.state=WorkflowState.PREFLIGHT; self.last_success:WorkflowState|None=None; self.session: str|None=None; self.mutated=False; self.baseline:dict|None=None
    def _at(self,state:WorkflowState, *, safe_oid: str | None = None, safe_root_hash: str | None = None)->None:
        self.state=state
        try: self.logger.write(state,"entered",session_id=self.session,last_successful_state=self.last_success,safe_oid=safe_oid,safe_root_hash=safe_root_hash)
        except Exception as error:
            code=EXIT_RECOVERY_REQUIRED if self.mutated else 2
            message="Audit log failed after mutation; run recover." if self.mutated else "Audit log could not be written before mutation."
            raise SyncError("logging_failed",message,code) from None
        self.last_success=state
    def _require_adapter_contract(self) -> None:
        """Fail before preflight (and therefore before mutations) for incomplete fakes/adapters."""
        missing=[name for name in self._REQUIRED_METHODS if not callable(getattr(self.adapters,name,None))]
        if missing:
            raise SyncError("adapter_contract_invalid","Launch adapter is incomplete; no sync action was started.",2)
    def _call(self,name:str,*args:Any)->Any: return getattr(self.adapters,name)(*args)
    def _skip(self,state:WorkflowState)->None:
        self.state=state; self.logger.write(state,"skipped",session_id=self.session,last_successful_state=self.last_success); self.last_success=state
    def _reconcile_three_way(self,base:str)->str:
        """Return apply/noop; conflicts are archived/quarantined by adapters when available."""
        try: state=self.adapters.state() # Missing state is intentionally a hard bootstrap boundary.
        except SyncError as error:
            if error.code == "state_missing":
                raise SyncError("bootstrap_required","No applied baseline exists; run bootstrap before launch.",EXIT_CONFLICT) from None
            raise
        live=self.adapters.live_manifest(); self.baseline=live; remote=self.adapters.remote_manifest(base,"reconcile")
        if live["root_hash"]==remote["root_hash"]: return "noop"
        if not state.last_applied_remote_commit or not state.last_applied_manifest_root_hash: raise SyncError("bootstrap_required","No applied baseline exists; run bootstrap before launch.",EXIT_CONFLICT)
        live_advanced=live["root_hash"]!=state.last_applied_manifest_root_hash; remote_advanced=base!=state.last_applied_remote_commit
        if not live_advanced and remote_advanced: return "apply"
        if live_advanced and not remote_advanced: return "noop"
        if live_advanced and remote_advanced:
            self.adapters.quarantine(live)
            raise SyncError("save_conflict","Live and remote saves both advanced; live save was quarantined.",EXIT_CONFLICT)
        raise SyncError("reconcile_inconsistent","Save baselines are inconsistent; run recover.",EXIT_RECOVERY_REQUIRED)
    def run(self)->dict[str,str]:
        lock=None; manifest=None; safe_oid=None; safe_root_hash=None; archive_root=None; quarantine_root=None
        archive_id=None; quarantine_id=None
        def capture_destinations() -> None:
            nonlocal archive_id, quarantine_id, archive_root, quarantine_root
            archive_id = getattr(self.adapters, "last_archive_destination", archive_id)
            quarantine_id = getattr(self.adapters, "last_quarantine_destination", quarantine_id)
            archive_root = getattr(self.adapters, "last_archive_root", archive_root)
            quarantine_root = getattr(self.adapters, "last_quarantine_root", quarantine_root)
        def recovery_details() -> dict[str, str]:
            """The CLI contract contains only stable identifiers, never paths or causes."""
            details = {"machine_id": self.config.machine_id, "last_state": self.state.value,
                       "next_command": "grim-dawn-sync recover"}
            if self.session: details["session_id"] = self.session
            if safe_oid: details["local_commit"] = safe_oid
            if safe_root_hash: details["root_hash"] = safe_root_hash
            if archive_id: details["archive"] = archive_id
            if quarantine_id: details["quarantine"] = quarantine_id
            return details
        try:
            self._require_adapter_contract()
            self._at(WorkflowState.PREFLIGHT); self._call("preflight")
            self._at(WorkflowState.FETCH_REMOTE); status=self._call("fetch_and_reconcile")
            self._at(WorkflowState.RECONCILE)
            if getattr(status,"relation",status) in {"ahead","diverged","unborn"}: raise SyncError("vault_not_reconciled","Vault must be synchronized before launch.",EXIT_CONFLICT)
            base=self._call("remote_oid")
            if not base: raise SyncError("remote_main_missing","Remote main is missing; run bootstrap first.",EXIT_CONFLICT)
            try:
                action=self._reconcile_three_way(base)
            finally:
                capture_destinations()
            self._at(WorkflowState.ACQUIRE_LOCK); lock=self._call("acquire",base); self.mutated=True; self.session=lock.session.session_id
            baseline=None
            if action=="apply":
                plan=self._call("prepare_remote_restore",base,self.session); self._at(WorkflowState.ARCHIVE_BEFORE_RESTORE); plan=self._call("archive_before_restore",plan); self._at(WorkflowState.APPLY_REMOTE_SAVE); self._call("apply_remote_save",plan)
                baseline=self._call("wait_save_stable"); self.baseline=baseline or self.baseline
            else:
                self._skip(WorkflowState.ARCHIVE_BEFORE_RESTORE); self._skip(WorkflowState.APPLY_REMOTE_SAVE)
            self._call("launch",lambda value:self._at(WorkflowState(value)))
            self._at(WorkflowState.WAIT_SAVE_STABLE)
            try: stable=self._call("wait_save_stable")
            except SyncError as original:
                try: quarantine_root=self._call("rescue_raw",None); capture_destinations()
                except Exception: raise SyncError("rescue_incomplete","Save stability failed and rescue archive could not be confirmed; run recover.",EXIT_RECOVERY_REQUIRED) from None
                raise
            self._at(WorkflowState.VALIDATE_SAVE)
            try: manifest=self._call("validate",stable,self.baseline or baseline)
            except SyncError:
                try:
                    quarantine_root=self._call("rescue_raw",stable); capture_destinations()
                except Exception:
                    raise SyncError("rescue_incomplete","Save validation failed and rescue archive could not be confirmed; run recover.",EXIT_RECOVERY_REQUIRED) from None
                raise
            self._at(WorkflowState.ARCHIVE_AFTER_GAME)
            archive_root=self._call("archive_after_game",manifest); capture_destinations()
            oid=self._call("snapshot",self.session,manifest,lambda value:self._at(WorkflowState(value))); safe_oid=oid; safe_root_hash=manifest["root_hash"]
            self._call("mark_committed",lock,oid,safe_root_hash)
            self._at(WorkflowState.PUSH,safe_oid=safe_oid,safe_root_hash=safe_root_hash); pushed=self._call("push",oid); safe_oid=pushed
            self._at(WorkflowState.RELEASE_LOCK)
            self._call("release",lock,pushed,manifest)
            self._at(WorkflowState.COMPLETE,safe_oid=pushed,safe_root_hash=(manifest or {}).get("root_hash")); return {"state":"COMPLETE","commit":pushed}
        except SyncError as error:
            capture_destinations()
            if self.mutated:
                # Preserve adapter-supplied diagnostic fields while giving every
                # post-lock failure the same recovery handoff contract.
                error.details = {**error.details, **recovery_details()}
            if error.code == "logging_failed": raise
            try: self.logger.write(self.state,"failed",error.code,session_id=self.session,last_successful_state=self.last_success,safe_oid=safe_oid,safe_root_hash=safe_root_hash,archive_root=archive_root,quarantine_root=quarantine_root,archive_id=archive_id,quarantine_id=quarantine_id)
            except Exception:
                # Before any mutation log failures are configuration; after it recovery is required.
                if lock is None: raise SyncError("logging_failed","Audit log could not be written before mutation.",2) from None
                raise SyncError("logging_failed","Audit log failed after a local mutation; run recover.",EXIT_RECOVERY_REQUIRED) from None
            raise
        except Exception:
            capture_destinations()
            try: self.logger.write(self.state,"failed","unexpected_failure",session_id=self.session,last_successful_state=self.last_success,safe_oid=safe_oid,safe_root_hash=safe_root_hash,archive_root=archive_root,quarantine_root=quarantine_root,archive_id=archive_id,quarantine_id=quarantine_id)
            except Exception: pass
            code = EXIT_RECOVERY_REQUIRED if self.mutated else 2
            error = SyncError("unexpected_failure","Launch workflow stopped; run recover before another launch.",code)
            if self.mutated: error.details = recovery_details()
            raise error from None
