"""Fail-closed launch orchestration.

The state machine deliberately owns policy.  Adapters own I/O, which keeps
the dangerous path entirely fake-testable.
"""
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
import json
from pathlib import Path
from typing import Any, Callable, Protocol, runtime_checkable
import uuid
import re

from grim_dawn_sync.config import SyncConfig
from grim_dawn_sync.errors import EXIT_CONFLICT, EXIT_RECOVERY_REQUIRED, EXIT_VALIDATION, SyncError
from grim_dawn_sync.git_vault import GitVault
from grim_dawn_sync.launcher import DPYesLauncher
from grim_dawn_sync.manifest import _reject_unsafe, build_manifest, stable_manifest
from grim_dawn_sync.session_lock import acquire_lock, release_bookmark_lock, release_lock, release_without_publish
from grim_dawn_sync.session_start import (
    SESSION_START_ID_PATTERN,
    create_session_start_archive,
    extract_session_start_archive,
    read_session_start_metadata,
    session_start_archive_manifest,
)
from grim_dawn_sync.snapshot import _copy_verified, _manifest, apply_restore, archive_before_restore, plan_restore
from grim_dawn_sync.state import SyncState, load_state, save_state_if_unchanged
from grim_dawn_sync.validation import destructive_change, validate_players
from grim_dawn_sync.bookmarks import create_displaced_head_bookmark_locked
from grim_dawn_sync.selection import SelectionPlan, SelectionRegistry, allowed_exit_disposition_transition


class WorkflowState(str, Enum):
    PREFLIGHT="PREFLIGHT"; FETCH_REMOTE="FETCH_REMOTE"; RECONCILE="RECONCILE"; BUILD_CATALOG="BUILD_CATALOG"; WAIT_SELECTION="WAIT_SELECTION"; REVALIDATE_SELECTION="REVALIDATE_SELECTION"; ACQUIRE_LOCK="ACQUIRE_LOCK"; SESSION_START_SNAPSHOT="SESSION_START_SNAPSHOT"; BOOKMARK_DISPLACED_REMOTE="BOOKMARK_DISPLACED_REMOTE"
    ARCHIVE_BEFORE_RESTORE="ARCHIVE_BEFORE_RESTORE"; APPLY_REMOTE_SAVE="APPLY_REMOTE_SAVE"; START_DPYES="START_DPYES"
    WAIT_GAME_START="WAIT_GAME_START"; WAIT_GAME_EXIT="WAIT_GAME_EXIT"; WAIT_SAVE_STABLE="WAIT_SAVE_STABLE"
    VALIDATE_SAVE="VALIDATE_SAVE"; ARCHIVE_AFTER_GAME="ARCHIVE_AFTER_GAME"; UPDATE_VAULT="UPDATE_VAULT"
    EXIT_DISPOSITION_CONFIRM="EXIT_DISPOSITION_CONFIRM"; RESTORE_SESSION_START="RESTORE_SESSION_START"
    COMMIT="COMMIT"; PUSH="PUSH"; RELEASE_LOCK="RELEASE_LOCK"; COMPLETE="COMPLETE"


class JsonlLog:
    """Best-effort privacy-safe audit log.  Logging must never mask recovery."""
    def __init__(self, path: Path, *, machine_id: str | None = None) -> None:
        self.path, self.machine_id = Path(path), machine_id
    def write(self, state: WorkflowState, event: str, code: str | None = None, *, session_id: str | None = None, last_successful_state: WorkflowState | None = None, safe_oid: str | None = None, safe_root_hash: str | None = None, archive_root: str | None = None, quarantine_root: str | None = None, archive_id: str | None = None, quarantine_id: str | None = None, remote_check_status: str | None = None) -> None:
        # Values are allow-listed identifiers only; callers never pass paths or exception text.
        row: dict[str, str] = {"schema_version":"1.0.0", "timestamp_utc":datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00","Z"), "state":state.value, "event":event}
        if self.machine_id and re.fullmatch(r"[A-Za-z0-9._-]{1,128}",self.machine_id): row["machine_id"] = self.machine_id
        if session_id and re.fullmatch(r"[A-Za-z0-9._-]{1,128}",session_id): row["session_id"] = session_id
        if last_successful_state: row["last_successful_state"] = last_successful_state.value
        if safe_oid and re.fullmatch(r"[0-9a-f]{40}(?:[0-9a-f]{24})?",safe_oid): row["safe_oid"] = safe_oid
        if safe_root_hash and re.fullmatch(r"[0-9a-f]{64}",safe_root_hash): row["safe_root_hash"] = safe_root_hash
        if archive_root and re.fullmatch(r"[0-9a-f]{64}",archive_root): row["archive_root"] = archive_root
        if quarantine_root and re.fullmatch(r"[0-9a-f]{64}",quarantine_root): row["quarantine_root"] = quarantine_root
        # These are basename identifiers generated by us, never save-relative paths.
        if archive_id and re.fullmatch(r"save-[0-9TZ-]+-[0-9a-f]{16}-[0-9a-f]{32}", archive_id): row["archive_id"] = archive_id
        if quarantine_id and re.fullmatch(r"save-[0-9TZ-]+-[0-9a-f]{16}-[0-9a-f]{32}", quarantine_id): row["quarantine_id"] = quarantine_id
        # Only the check's own status; never a commit OID, root hash, path, or remote URL.
        if remote_check_status in ("ok", "failed", "skipped"): row["remote_check_status"] = remote_check_status
        if code:
            row["code"] = code
            row["next_command"] = "grim-dawn-sync status" if code in {"vault_not_reconciled","remote_main_missing","bootstrap_required"} else "grim-dawn-sync recover"
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self.path.open("a", encoding="utf-8", newline="\n") as out: out.write(json.dumps(row, sort_keys=True, separators=(",",":"))+"\n")


@runtime_checkable
class WorkflowAdapters(Protocol):
    """The complete launch boundary.  It is checked before any I/O occurs."""
    def preflight(self) -> None: ...
    def state(self) -> SyncState: ...
    def live_manifest(self) -> dict: ...
    def remote_manifest(self, base: str, session: str) -> dict: ...
    def fetch_and_reconcile(self) -> Any: ...
    def remote_oid(self) -> str | None: ...
    def acquire(self, base: str, *, expected_pre_state: SyncState | None = None) -> Any: ...
    def prepare_remote_restore(self, base: str, session: str) -> Any: ...
    def archive_before_restore(self, plan: Any) -> Any: ...
    def apply_remote_save(self, plan: Any) -> Any: ...
    def launch(self, hook: Callable[[str], None]) -> Any: ...
    def wait_save_stable(self) -> dict: ...
    def validate(self, manifest: dict, baseline: dict | None) -> dict: ...
    def archive_after_game(self, manifest: dict) -> str: ...
    def rescue_raw(self, manifest: dict | None) -> str: ...
    def quarantine(self, manifest: dict) -> str: ...
    def snapshot(self, session: str, manifest: dict, hook: Callable[[str], None]) -> str: ...
    def mark_committed(self, lock: Any, oid: str, root_hash: str) -> None: ...
    def push(self, oid: str) -> str: ...
    def release(self, lock: Any, oid: str, manifest: dict) -> None: ...
    def release_without_publish(self, lock: Any) -> None: ...


class DomainAdapters:
    def __init__(self, config: SyncConfig, local_root: Path) -> None:
        self.config, self.local_root = config, Path(local_root); self.vault = GitVault(config.vault_repo, remote=config.remote, branch=config.branch)
        self.last_archive_destination: str | None = None
        self.last_quarantine_destination: str | None = None
        self.last_archive_root: str | None = None
        self.last_quarantine_root: str | None = None
        self._selection_lock: Any | None = None
        self._selection_original_state: SyncState | None = None
        self._committed_state: SyncState | None = None
    @property
    def state_path(self) -> Path: return self.local_root / "state.json"
    def preflight(self) -> None:
        self.vault.preflight()
        # Refuse before lock acquisition if a configured process is present or unidentifiable.
        scan=DPYesLauncher(self.config)._scan()
        names={name.casefold() for name in self.config.game_process_names} | {"dpyes.exe"}
        if any(item.name.casefold() in names for item in scan.processes):
            raise SyncError("game_already_running","Configured Grim Dawn process already exists.",5)
    def state(self) -> SyncState: return load_state(self.state_path)
    def live_manifest(self) -> dict: return stable_manifest(self.config.save_root, machine_id=self.config.machine_id, retries=self.config.stable_scan_retries, window_seconds=0)
    def remote_manifest(self, base: str, session: str) -> dict:
        return self.vault.read_manifest(base)
    def fetch_and_reconcile(self): return self.vault.update_fast_forward()
    def remote_oid(self) -> str | None: return self.vault.remote_oid()
    def bookmark_displaced_remote(self, commit: str, plan: SelectionPlan) -> None:
        """Preserve the exact old remote head before any restore or main push."""
        if not commit:
            raise SyncError("remote_main_missing", "Remote main is missing; no selection was applied.", EXIT_CONFLICT)
        if self._selection_lock is None or self._selection_original_state is None:
            raise SyncError("adapter_contract_invalid", "Selection bookmark has no recoverable lock context.", EXIT_RECOVERY_REQUIRED)
        create_displaced_head_bookmark_locked(
            self.vault,
            self._selection_lock,
            self._selection_original_state,
            commit,
            state_path=self.state_path,
            created_by=self.config.machine_id,
        )
    def bind_remote_identity(self, expected: tuple[str, str]) -> None:
        self.vault.bind_remote_identity(expected)
    def align_selection_base(self, expected_remote_head: str) -> None:
        self.vault.align_head_to_remote(expected_remote_head)
    def acquire(self, base: str, *, expected_pre_state: SyncState | None = None):
        original = expected_pre_state if expected_pre_state is not None else self.state()
        lock = acquire_lock(
            self.vault, self.config.machine_id, base,
            state_path=self.state_path, expected_pre_state=original,
        )
        self._selection_lock = lock
        self._selection_original_state = original
        return lock
    def prepare_remote_restore(self, base: str, session: str):
        source=self.local_root/"staging"/session
        self.vault.extract_save(base,source,machine_id=self.config.machine_id,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds)
        return plan_restore(source,self.config.save_root,self.local_root/"archives",self.local_root/"recovery",machine_id=self.config.machine_id,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds,session_id=session)
    def archive_before_restore(self, plan): return archive_before_restore(plan,machine_id=self.config.machine_id,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds)
    def session_start_snapshot(self, expected_live_root_hash: str, *, session_id: str, launched_from_candidate_kind: str) -> str:
        """Archive the exact pre-launch live save; runs once, right after lock acquisition."""
        manifest = stable_manifest(
            self.config.save_root, machine_id=self.config.machine_id,
            retries=self.config.stable_scan_retries, window_seconds=self.config.stable_window_seconds,
        )
        if manifest.get("root_hash") != expected_live_root_hash:
            raise SyncError("selection_stale", "Live save changed after lock acquisition; run recover.", EXIT_RECOVERY_REQUIRED)
        return create_session_start_archive(
            self.local_root / "archives", self.config.save_root, manifest=manifest, machine_id=self.config.machine_id,
            session_id=session_id, launched_from_candidate_kind=launched_from_candidate_kind,
            retries=self.config.stable_scan_retries, window_seconds=self.config.stable_window_seconds,
        )
    def release_unmutated_lock(self, lock: Any) -> None:
        """Cleanly abandon a lock that was acquired but never used to mutate anything.

        Only valid immediately after ``acquire``, before any commit or restore.
        """
        if self._selection_original_state is None:
            raise SyncError("adapter_contract_invalid", "No recoverable original state for lock release.", EXIT_RECOVERY_REQUIRED)
        release_bookmark_lock(self.vault, lock, self._selection_original_state, state_path=self.state_path)
    def release_without_publish(self, lock: Any) -> None:
        """Release a lock after ``local-only``/``restore-startup`` without any push.

        Valid any time after ``acquire``, once every local-only mutation
        (session-start snapshot, ``archive_after_game``, and an optional
        restore-startup swap) is finished.  ``last_applied_remote_commit`` and
        ``last_applied_manifest_root_hash`` are left exactly as they were.
        """
        if self._selection_original_state is None:
            raise SyncError("adapter_contract_invalid", "No recoverable original state for lock release.", EXIT_RECOVERY_REQUIRED)
        release_without_publish(self.vault, lock, self._selection_original_state, state_path=self.state_path)
    def prepare_local_restore(self, archive_id: str, session: str):
        """Stage a verified session-start archive's save tree (never its metadata sidecar)."""
        archives_root = self.local_root / "archives"
        archive = archives_root / archive_id
        if not SESSION_START_ID_PATTERN.fullmatch(archive_id) or archive.parent != archives_root:
            raise SyncError("candidate_not_authorized", "Selected session-start archive id is invalid.", EXIT_VALIDATION)
        _reject_unsafe(archives_root)
        _reject_unsafe(archive)
        if not archive.is_dir():
            raise SyncError("candidate_not_authorized", "Selected session-start archive is unavailable.", EXIT_VALIDATION)
        metadata = read_session_start_metadata(archive)
        manifest = session_start_archive_manifest(archive, machine_id=self.config.machine_id)
        if manifest["root_hash"] != metadata["root_hash"]:
            raise SyncError("candidate_not_authorized", "Selected session-start archive no longer matches its record.", EXIT_VALIDATION)
        staged = self.local_root / "staging" / session
        extract_session_start_archive(archive, staged, expected_manifest=manifest, machine_id=self.config.machine_id)
        return plan_restore(
            staged, self.config.save_root, self.local_root / "archives", self.local_root / "recovery",
            machine_id=self.config.machine_id, retries=self.config.stable_scan_retries,
            window_seconds=self.config.stable_window_seconds, session_id=session,
        )
    def apply_remote_save(self, plan): return apply_restore(plan,self.local_root/"recovery",machine_id=self.config.machine_id,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds)
    def launch(self, hook: Callable[[str],None]): return DPYesLauncher(self.config,state_hook=hook).run()
    def wait_save_stable(self) -> dict: return stable_manifest(self.config.save_root,machine_id=self.config.machine_id,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds)
    def validate(self, manifest: dict, baseline: dict | None = None) -> dict:
        result=validate_players(self.config.save_root,manifest)
        if not result.get("ok"): raise SyncError(result.get("classification","save_invalid"),"Save validation did not permit snapshot.",EXIT_VALIDATION)
        # Grim Dawn can legitimately rewrite the same save files to a slightly
        # smaller encoding.  Keep blocking structural loss, but do not treat a
        # total-byte decrease by itself as proof that save data was deleted.
        if baseline:
            change = destructive_change(baseline, manifest)
            structural_loss = {
                "character_count_decreased",
                "player_gdc_missing",
                "files_removed",
            }
            if structural_loss.intersection(change["reasons"]):
                self.quarantine(manifest); raise SyncError("destructive_change","Save lost characters or files from its launch baseline; it was quarantined.",EXIT_VALIDATION)
        return manifest
    def _unique_destination(self, category: str, manifest: dict) -> Path:
        # mkdir("x") is performed by _copy_verified; UUID avoids every prior run.
        stamp=datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        return self.local_root/category/f"save-{stamp}-{manifest['root_hash'][:16]}-{uuid.uuid4().hex}"
    def _destination_root(self, category: str) -> Path:
        """Create the local archive root without traversing a link/reparse ancestor."""
        root = self.local_root / category
        ancestors = tuple(reversed((root, *root.parents)))
        def inspect_existing() -> None:
            for ancestor in ancestors:
                try:
                    ancestor.lstat()
                except FileNotFoundError:
                    continue
                except OSError as error:
                    raise SyncError("snapshot_root_unavailable", "Local snapshot root could not be inspected.", EXIT_VALIDATION) from error
                _reject_unsafe(ancestor)
                if not ancestor.is_dir():
                    raise SyncError("snapshot_root_unsafe", "Local snapshot root has a non-directory ancestor.", EXIT_VALIDATION)
        # Inspect first: mkdir(parents=True) must never traverse an existing
        # symlink, junction, mount reparse point, or other redirection.
        inspect_existing()
        try:
            root.mkdir(parents=True, exist_ok=True)
        except OSError as error:
            raise SyncError("snapshot_root_unavailable", "Local snapshot root could not be created.", EXIT_VALIDATION) from error
        # Recheck the full chain after creation to detect replacement races.
        inspect_existing()
        return root
    def _new_destination(self, category: str, manifest: dict) -> Path:
        self._destination_root(category)
        # UUID makes a duplicate root hash a new safe archive, never an overwrite.
        return self._unique_destination(category, manifest)
    def quarantine(self, manifest: dict) -> str:
        dest=self._new_destination("quarantine",manifest)
        _copy_verified(self.config.save_root,dest,manifest,self.config.machine_id,self.config.stable_scan_retries,0,validate_players)
        self.last_quarantine_destination = dest.name
        self.last_quarantine_root = manifest["root_hash"]
        return manifest["root_hash"]
    def archive_after_game(self, manifest: dict) -> str:
        dest=self._new_destination("archives",manifest)
        _copy_verified(self.config.save_root,dest,manifest,self.config.machine_id,self.config.stable_scan_retries,0,validate_players)
        self.last_archive_destination = dest.name
        self.last_archive_root = manifest["root_hash"]
        return manifest["root_hash"]
    def rescue_raw(self, manifest: dict | None) -> str:
        """Validation-permissive, local-only copy; tree safety and hash integrity remain strict."""
        raw=manifest or build_manifest(self.config.save_root,machine_id=self.config.machine_id)
        dest=self._new_destination("quarantine",raw)
        _copy_verified(self.config.save_root,dest,raw,self.config.machine_id,1,0,lambda _root, _manifest: {"ok":True})
        self.last_quarantine_destination = dest.name
        self.last_quarantine_root = raw["root_hash"]
        return raw["root_hash"]
    def snapshot(self, session: str, manifest: dict, hook: Callable[[str],None]) -> str:
        # Requiring the already-validated manifest prevents an unbound snapshot.
        return self.vault.snapshot(self.config.save_root,machine_id=self.config.machine_id,session_id=session,retries=self.config.stable_scan_retries,window_seconds=self.config.stable_window_seconds,expected_manifest=manifest,state_hook=hook)
    def mark_committed(self, lock: object, oid: str, root_hash: str) -> None:
        s = lock.session
        current = load_state(self.state_path)
        if (
            current.phase != "lock_held"
            or current.session_id != s.session_id
            or current.machine_id != s.machine_id
            or current.base_commit != s.base_commit
            or current.lock_oid != lock.oid
            or current.local_tag != lock.local_tag
        ):
            raise SyncError("recovery_state_changed", "Lock state changed before commit persistence.", EXIT_RECOVERY_REQUIRED)
        committed = SyncState(
            last_applied_manifest_root_hash=root_hash,
            session_id=s.session_id, machine_id=s.machine_id, base_commit=s.base_commit,
            lock_oid=lock.oid, local_tag=lock.local_tag, phase="committed", local_commit=oid,
        )
        try:
            save_state_if_unchanged(self.state_path, current, committed)
        except SyncError as error:
            raise SyncError(
                "recovery_state_changed", "Lock state changed before commit persistence.",
                EXIT_RECOVERY_REQUIRED, {**error.details, "session_id": s.session_id},
            ) from error
        self._committed_state = committed
    def push(self, oid: str) -> str: return self.vault.push(oid)
    def release(self, lock: object, oid: str, manifest: dict) -> None:
        expected = self._committed_state
        if expected is None:
            raise SyncError("adapter_contract_invalid", "Committed state was not bound before release.", EXIT_RECOVERY_REQUIRED)
        release_lock(
            self.vault,
            lock,
            oid,
            state_path=self.state_path,
            confirmed_root_hash=manifest["root_hash"],
            expected_state=expected,
        )
        self._committed_state = None


class LaunchWorkflow:
    _REQUIRED_METHODS = (
        "preflight", "state", "live_manifest", "remote_manifest", "fetch_and_reconcile", "remote_oid", "acquire",
        "prepare_remote_restore", "archive_before_restore", "apply_remote_save", "launch", "wait_save_stable", "validate",
        "archive_after_game", "rescue_raw", "quarantine", "snapshot", "mark_committed", "push", "release",
    )
    def __init__(self,config:SyncConfig,local_root:Path,*,adapters:WorkflowAdapters|None=None,logger:JsonlLog|None=None)->None:
        self.config,self.local_root=config,Path(local_root); self.adapters=DomainAdapters(config,self.local_root) if adapters is None else adapters
        self.logger=JsonlLog(self.local_root/"logs"/"launch.jsonl",machine_id=config.machine_id) if logger is None else logger; self.state=WorkflowState.PREFLIGHT; self.last_success:WorkflowState|None=None; self.session: str|None=None; self.mutated=False; self.baseline:dict|None=None
    def _at(self,state:WorkflowState, *, safe_oid: str | None = None, safe_root_hash: str | None = None)->None:
        self.state=state
        try: self.logger.write(state,"entered",session_id=self.session,last_successful_state=self.last_success,safe_oid=safe_oid,safe_root_hash=safe_root_hash)
        except Exception as error:
            code=EXIT_RECOVERY_REQUIRED if self.mutated else 2
            message="Audit log failed after mutation; run recover." if self.mutated else "Audit log could not be written before mutation."
            raise SyncError("logging_failed",message,code) from None
        self.last_success=state
    # Needed only by the selection path.  ``run`` never takes a session-start
    # snapshot, so these stay out of _REQUIRED_METHODS.
    _SELECTION_REQUIRED_METHODS = ("session_start_snapshot", "release_unmutated_lock", "release_without_publish")
    def _require_adapter_contract(self, *, extra: tuple[str, ...] = ()) -> None:
        """Fail before preflight (and therefore before mutations) for incomplete fakes/adapters."""
        missing=[name for name in (*self._REQUIRED_METHODS, *extra) if not callable(getattr(self.adapters,name,None))]
        if missing:
            raise SyncError("adapter_contract_invalid","Launch adapter is incomplete; no sync action was started.",2)
    def _call(self,name:str,*args:Any)->Any: return getattr(self.adapters,name)(*args)
    def _skip(self,state:WorkflowState)->None:
        self.state=state; self.logger.write(state,"skipped",session_id=self.session,last_successful_state=self.last_success); self.last_success=state
    def _reconcile_three_way(self,base:str)->str:
        """Return apply/noop; conflicts are archived/quarantined by adapters when available."""
        try: state=self.adapters.state() # Missing state is intentionally a hard bootstrap boundary.
        except SyncError as error:
            if error.code == "state_missing":
                raise SyncError("bootstrap_required","No applied baseline exists; run bootstrap before launch.",EXIT_CONFLICT) from None
            raise
        live=self.adapters.live_manifest(); self.baseline=live; remote=self.adapters.remote_manifest(base,"reconcile")
        if live["root_hash"]==remote["root_hash"]: return "noop"
        if not state.last_applied_remote_commit or not state.last_applied_manifest_root_hash: raise SyncError("bootstrap_required","No applied baseline exists; run bootstrap before launch.",EXIT_CONFLICT)
        live_advanced=live["root_hash"]!=state.last_applied_manifest_root_hash; remote_advanced=base!=state.last_applied_remote_commit
        if not live_advanced and remote_advanced: return "apply"
        if live_advanced and not remote_advanced: return "noop"
        if live_advanced and remote_advanced:
            self.adapters.quarantine(live)
            raise SyncError("save_conflict","Live and remote saves both advanced; live save was quarantined.",EXIT_CONFLICT)
        raise SyncError("reconcile_inconsistent","Save baselines are inconsistent; run recover.",EXIT_RECOVERY_REQUIRED)

    def execute_selection_plan(self, plan: SelectionPlan, registry: SelectionRegistry, *,
                               context_revalidate: Callable[[str], None] | None = None,
                               exit_disposition_gate: Callable[[str], str] | None = None) -> dict[str, str]:
        """Execute one canonical selection only after its final stale check.

        This intentionally leaves the legacy ``run`` path intact while CLI/UI
        adapters migrate.  Every operation through ``WAIT_SELECTION`` is
        read-only; the canonical plan returned by ``revalidate`` is the only
        object trusted after that boundary.
        """
        lock = None; manifest: dict | None = None; safe_oid: str | None = None; safe_root_hash: str | None = None
        acquire_started = False
        session_start_archive_id: str | None = None
        archive_id: str | None = None; quarantine_id: str | None = None
        archive_root: str | None = None; quarantine_root: str | None = None
        def capture_destinations() -> None:
            nonlocal archive_id, quarantine_id, archive_root, quarantine_root
            archive_id = getattr(self.adapters, "last_archive_destination", archive_id)
            quarantine_id = getattr(self.adapters, "last_quarantine_destination", quarantine_id)
            archive_root = getattr(self.adapters, "last_archive_root", archive_root)
            quarantine_root = getattr(self.adapters, "last_quarantine_root", quarantine_root)
        def recovery_details() -> dict[str, str]:
            details: dict[str, str] = {"last_state": self.state.value, "next_command": "grim-dawn-sync recover"}
            if re.fullmatch(r"[A-Za-z0-9._-]{1,128}", self.config.machine_id): details["machine_id"] = self.config.machine_id
            if self.session and re.fullmatch(r"[A-Za-z0-9._-]{1,128}", self.session): details["session_id"] = self.session
            if safe_oid and re.fullmatch(r"[0-9a-f]{40}(?:[0-9a-f]{24})?", safe_oid): details["local_commit"] = safe_oid
            if safe_root_hash and re.fullmatch(r"[0-9a-f]{64}", safe_root_hash): details["root_hash"] = safe_root_hash
            if archive_id and re.fullmatch(r"save-[0-9TZ-]+-[0-9a-f]{16}-[0-9a-f]{32}", archive_id): details["archive"] = archive_id
            if quarantine_id and re.fullmatch(r"save-[0-9TZ-]+-[0-9a-f]{16}-[0-9a-f]{32}", quarantine_id): details["quarantine"] = quarantine_id
            return details
        def require_live_root(expected: str, *, post_lock: bool) -> dict:
            observed = self._call("live_manifest")
            if observed.get("root_hash") != expected:
                raise SyncError(
                    "selection_stale",
                    "Live save changed after selection; reload versions." if not post_lock else "Live save changed after lock acquisition; run recover.",
                    EXIT_RECOVERY_REQUIRED if post_lock else EXIT_CONFLICT,
                )
            return observed
        try:
            self._require_adapter_contract(extra=self._SELECTION_REQUIRED_METHODS)
            self._at(WorkflowState.PREFLIGHT); self._call("preflight")
            self._at(WorkflowState.REVALIDATE_SELECTION)
            canonical = registry.revalidate(
                plan, live_manifest=lambda: self._call("live_manifest"), remote_head=lambda: self._call("remote_oid"),
            )
            # No state, lock, archive, live-save, or vault mutation happened
            # before the registry returned this canonical capability.
            current_live = require_live_root(canonical.expected_live_root_hash, post_lock=False)
            # A "live" selection has no later restore step, so its selected
            # root must already equal the current live root.  A session_start
            # selection *does* have a later local-archive restore step (like a
            # remote/history/bookmark commit does), so it is exempt here too.
            if (
                current_live.get("root_hash") != canonical.selected_root_hash
                and canonical.selected_commit is None
                and canonical.candidate_kind != "session_start"
            ):
                raise SyncError("selection_stale", "Save data changed while selection was open; reload versions.", EXIT_CONFLICT)
            self.baseline = current_live
            if canonical.expected_context_digest is not None:
                if context_revalidate is None:
                    raise SyncError("adapter_contract_invalid", "Selection context cannot be revalidated.", EXIT_CONFLICT)
                context_revalidate(canonical.expected_context_digest)
            if canonical.expected_remote_identity is not None:
                binder = getattr(self.adapters, "bind_remote_identity", None)
                if not callable(binder):
                    raise SyncError("adapter_contract_invalid", "Remote identity cannot be bound.", EXIT_CONFLICT)
                binder(canonical.expected_remote_identity)
            self._at(WorkflowState.ACQUIRE_LOCK)
            acquire_started = True
            expected_pre_state = getattr(context_revalidate, "expected_pre_state", None)
            if expected_pre_state is None:
                lock = self._call("acquire", canonical.expected_remote_head)
            else:
                lock = self.adapters.acquire(
                    canonical.expected_remote_head, expected_pre_state=expected_pre_state,
                )
            self.mutated = True; self.session = lock.session.session_id
            post_lock_live_root: str | None = None
            if canonical.expected_context_digest is not None:
                after_lock = getattr(context_revalidate, "after_lock", None)
                if not callable(after_lock):
                    raise SyncError("adapter_contract_invalid", "Post-lock selection context cannot be revalidated.", EXIT_RECOVERY_REQUIRED)
                attestation = after_lock(canonical.expected_context_digest, lock)
                if not isinstance(attestation, dict) or not isinstance(attestation.get("live_root_hash"), str):
                    raise SyncError("adapter_contract_invalid", "Post-lock selection context is incomplete.", EXIT_RECOVERY_REQUIRED)
                post_lock_live_root = attestation["live_root_hash"]
            # Close every live-save race before the first post-lock mutation,
            # including remote candidates whose selected root differs by design.
            if canonical.expected_context_digest is None:
                require_live_root(canonical.expected_live_root_hash, post_lock=True)
            elif post_lock_live_root != canonical.expected_live_root_hash:
                raise SyncError(
                    "selection_stale", "Live save changed after lock acquisition; run recover.",
                    EXIT_RECOVERY_REQUIRED,
                )
            # Unconditionally preserve the exact pre-launch live save, before any
            # restore, launch, or promotion touches it.  A failure here must
            # leave live untouched and must not force recovery: the lock is
            # cleanly abandoned instead, since nothing has mutated yet.
            self._at(WorkflowState.SESSION_START_SNAPSHOT)
            # Presence was already proven before preflight, so an incomplete
            # adapter can never get this far and strand a lock.
            session_start_fn = self.adapters.session_start_snapshot
            try:
                # The adapter re-scans live itself (it needs the full manifest
                # to archive, not just a root hash) and verifies that scan
                # against this already-established root before publishing.
                # Its returned archive ID is retained only for a possible
                # later restore-startup disposition; it is never surfaced to
                # a caller and never treated as an arbitrary path.
                session_start_archive_id = session_start_fn(
                    canonical.expected_live_root_hash, session_id=self.session,
                    launched_from_candidate_kind=canonical.candidate_kind,
                )
            except SyncError as session_start_error:
                # Nothing has mutated live/remote/state yet, so give the lock
                # back cleanly.  Only a *successful* release may clear
                # ``mutated``; if the release itself fails, the acquired lock
                # is still outstanding and recovery is genuinely required.
                try:
                    self.adapters.release_unmutated_lock(lock)
                except Exception:
                    pass
                else:
                    self.mutated = False
                raise session_start_error
            if canonical.bookmark_displaced_remote:
                self._at(WorkflowState.BOOKMARK_DISPLACED_REMOTE)
                bookmark = getattr(self.adapters, "bookmark_displaced_remote", None)
                if not callable(bookmark):
                    raise SyncError("adapter_contract_invalid", "Selection adapter cannot preserve remote data.", EXIT_RECOVERY_REQUIRED)
                bookmark(canonical.expected_remote_head, canonical)
            align = getattr(self.adapters, "align_selection_base", None)
            if not callable(align):
                raise SyncError("adapter_contract_invalid", "Selection adapter cannot align the Vault base.", EXIT_RECOVERY_REQUIRED)
            align(canonical.expected_remote_head)
            if canonical.selected_commit is not None:
                require_live_root(canonical.expected_live_root_hash, post_lock=True)
                restore_plan = self._call("prepare_remote_restore", canonical.selected_commit, self.session)
                self._at(WorkflowState.ARCHIVE_BEFORE_RESTORE)
                restore_plan = self._call("archive_before_restore", restore_plan)
                capture_destinations()
                require_live_root(canonical.expected_live_root_hash, post_lock=True)
                self._at(WorkflowState.APPLY_REMOTE_SAVE); self._call("apply_remote_save", restore_plan)
                try: restored = self._call("wait_save_stable")
                except SyncError:
                    quarantine_root = self._call("rescue_raw", None); capture_destinations(); raise
                if restored.get("root_hash") != canonical.selected_root_hash:
                    raise SyncError("selected_restore_mismatch", "Selected save did not match its verified manifest.", EXIT_RECOVERY_REQUIRED)
                self.baseline = restored
            elif canonical.candidate_kind == "session_start":
                require_live_root(canonical.expected_live_root_hash, post_lock=True)
                local_restore_fn = getattr(self.adapters, "prepare_local_restore", None)
                if not callable(local_restore_fn):
                    raise SyncError("adapter_contract_invalid", "Selection adapter cannot restore local session-start data.", EXIT_RECOVERY_REQUIRED)
                source_catalog = registry.catalog(canonical.catalog_token)
                source_candidate = source_catalog.candidate(canonical.candidate_id)
                archive_id = source_candidate.source_archive_id
                if not isinstance(archive_id, str) or not SESSION_START_ID_PATTERN.fullmatch(archive_id):
                    raise SyncError("candidate_not_authorized", "Selected session-start archive is not authorized.", EXIT_VALIDATION)
                restore_plan = local_restore_fn(archive_id, self.session)
                self._at(WorkflowState.ARCHIVE_BEFORE_RESTORE)
                restore_plan = self._call("archive_before_restore", restore_plan)
                capture_destinations()
                require_live_root(canonical.expected_live_root_hash, post_lock=True)
                self._at(WorkflowState.APPLY_REMOTE_SAVE); self._call("apply_remote_save", restore_plan)
                try: restored = self._call("wait_save_stable")
                except SyncError:
                    quarantine_root = self._call("rescue_raw", None); capture_destinations(); raise
                if restored.get("root_hash") != canonical.selected_root_hash:
                    raise SyncError("selected_restore_mismatch", "Selected save did not match its verified manifest.", EXIT_RECOVERY_REQUIRED)
                self.baseline = restored
            else:
                self._skip(WorkflowState.ARCHIVE_BEFORE_RESTORE); self._skip(WorkflowState.APPLY_REMOTE_SAVE)
            if canonical.mode == "launch":
                self._call("launch", lambda value: self._at(WorkflowState(value)))
                self._at(WorkflowState.WAIT_SAVE_STABLE)
                try: stable = self._call("wait_save_stable")
                except SyncError:
                    quarantine_root = self._call("rescue_raw", None); capture_destinations(); raise
            else:
                stable = self._call("wait_save_stable")
                if stable.get("root_hash") != canonical.selected_root_hash:
                    raise SyncError("selected_save_changed", "Selected save changed before promotion.", EXIT_RECOVERY_REQUIRED)
            self._at(WorkflowState.VALIDATE_SAVE)
            try: manifest = self._call("validate", stable, self.baseline)
            except SyncError:
                quarantine_root = self._call("rescue_raw", stable); capture_destinations(); raise
            if canonical.mode == "promote-only" and manifest.get("root_hash") != canonical.selected_root_hash:
                raise SyncError("selected_save_changed", "Validated save no longer matches the selected version.", EXIT_RECOVERY_REQUIRED)
            self._at(WorkflowState.ARCHIVE_AFTER_GAME); archive_root = self._call("archive_after_game", manifest); capture_destinations()
            if canonical.mode == "promote-only" and self._call("live_manifest").get("root_hash") != canonical.selected_root_hash:
                raise SyncError("selected_save_changed", "Selected save changed before publication.", EXIT_RECOVERY_REQUIRED)
            # The exit disposition was fixed before the game ever launched.
            # promote-only never launches, so it is always "publish" (enforced
            # when the plan was built) and never reaches this gate. A launch
            # may still be downgraded here, once, in the only safe direction:
            # away from publishing, never back toward it.
            final_disposition = canonical.exit_disposition
            if canonical.mode == "launch" and exit_disposition_gate is not None:
                self._at(WorkflowState.EXIT_DISPOSITION_CONFIRM)
                proposed = exit_disposition_gate(final_disposition)
                if proposed != final_disposition:
                    if not allowed_exit_disposition_transition(final_disposition, proposed):
                        raise SyncError(
                            "exit_disposition_transition_forbidden",
                            "Exit disposition may only be downgraded away from publishing.",
                            EXIT_CONFLICT,
                        )
                    final_disposition = proposed
            if final_disposition == "local-only":
                self._at(WorkflowState.RELEASE_LOCK)
                self.adapters.release_without_publish(lock)
                self._at(WorkflowState.COMPLETE, safe_oid=safe_oid, safe_root_hash=safe_root_hash)
                return {"state": "COMPLETE", "exit_disposition": "local-only"}
            if final_disposition == "restore-startup":
                if session_start_archive_id is None:
                    raise SyncError(
                        "adapter_contract_invalid",
                        "No session-start archive is available to restore.",
                        EXIT_RECOVERY_REQUIRED,
                    )
                local_restore_fn = getattr(self.adapters, "prepare_local_restore", None)
                if not callable(local_restore_fn):
                    raise SyncError("adapter_contract_invalid", "Selection adapter cannot restore local session-start data.", EXIT_RECOVERY_REQUIRED)
                self._at(WorkflowState.RESTORE_SESSION_START)
                restore_plan = local_restore_fn(session_start_archive_id, f"{self.session}-exit-restore")
                restore_plan = self._call("archive_before_restore", restore_plan)
                capture_destinations()
                self._call("apply_remote_save", restore_plan)
                try: restored = self._call("wait_save_stable")
                except SyncError:
                    quarantine_root = self._call("rescue_raw", None); capture_destinations(); raise
                if restored.get("root_hash") != restore_plan.source_manifest["root_hash"]:
                    raise SyncError(
                        "selected_restore_mismatch",
                        "Restored start-of-session save did not match its verified manifest.",
                        EXIT_RECOVERY_REQUIRED,
                    )
                self._at(WorkflowState.RELEASE_LOCK)
                self.adapters.release_without_publish(lock)
                self._at(WorkflowState.COMPLETE, safe_oid=safe_oid, safe_root_hash=restored.get("root_hash"))
                return {"state": "COMPLETE", "exit_disposition": "restore-startup"}
            oid = self._call("snapshot", self.session, manifest, lambda value: self._at(WorkflowState(value)))
            safe_oid = oid; safe_root_hash = manifest["root_hash"]; self._call("mark_committed", lock, oid, safe_root_hash)
            self._at(WorkflowState.PUSH, safe_oid=oid, safe_root_hash=manifest["root_hash"])
            pushed = self._call("push", oid)
            safe_oid = pushed
            if canonical.mode == "promote-only":
                published = self._call("remote_manifest", pushed, "selection-published")
                if published.get("root_hash") != canonical.selected_root_hash:
                    raise SyncError("selected_publish_mismatch", "Published save does not match the selected version.", EXIT_RECOVERY_REQUIRED)
            self._at(WorkflowState.RELEASE_LOCK); self._call("release", lock, pushed, manifest)
            self._at(WorkflowState.COMPLETE, safe_oid=pushed, safe_root_hash=manifest["root_hash"])
            return {"state": "COMPLETE", "commit": pushed, "exit_disposition": "publish"}
        except SyncError as error:
            capture_destinations()
            recovery_required = self.mutated or (acquire_started and error.code == "lock_push_unknown")
            if recovery_required:
                error = SyncError(error.code, error.message, EXIT_RECOVERY_REQUIRED, {**error.details, **recovery_details()})
            try:
                self.logger.write(self.state, "failed", error.code, session_id=self.session,
                                  last_successful_state=self.last_success, safe_oid=safe_oid, safe_root_hash=safe_root_hash,
                                  archive_root=archive_root, quarantine_root=quarantine_root,
                                  archive_id=archive_id, quarantine_id=quarantine_id)
            except Exception:
                pass
            raise error
        except Exception:
            capture_destinations()
            try:
                self.logger.write(self.state, "failed", "unexpected_failure", session_id=self.session,
                                  last_successful_state=self.last_success, safe_oid=safe_oid, safe_root_hash=safe_root_hash,
                                  archive_root=archive_root, quarantine_root=quarantine_root,
                                  archive_id=archive_id, quarantine_id=quarantine_id)
            except Exception:
                pass
            code = EXIT_RECOVERY_REQUIRED if self.mutated else 2
            error = SyncError("unexpected_failure", "Selection workflow stopped; run recover before trying again.", code)
            if self.mutated: error.details = recovery_details()
            raise error from None
    def run(self)->dict[str,str]:
        lock=None; manifest=None; safe_oid=None; safe_root_hash=None; archive_root=None; quarantine_root=None
        archive_id=None; quarantine_id=None
        def capture_destinations() -> None:
            nonlocal archive_id, quarantine_id, archive_root, quarantine_root
            archive_id = getattr(self.adapters, "last_archive_destination", archive_id)
            quarantine_id = getattr(self.adapters, "last_quarantine_destination", quarantine_id)
            archive_root = getattr(self.adapters, "last_archive_root", archive_root)
            quarantine_root = getattr(self.adapters, "last_quarantine_root", quarantine_root)
        def recovery_details() -> dict[str, str]:
            """The CLI contract contains only stable identifiers, never paths or causes."""
            details = {"machine_id": self.config.machine_id, "last_state": self.state.value,
                       "next_command": "grim-dawn-sync recover"}
            if self.session: details["session_id"] = self.session
            if safe_oid: details["local_commit"] = safe_oid
            if safe_root_hash: details["root_hash"] = safe_root_hash
            if archive_id: details["archive"] = archive_id
            if quarantine_id: details["quarantine"] = quarantine_id
            return details
        try:
            self._require_adapter_contract()
            self._at(WorkflowState.PREFLIGHT); self._call("preflight")
            self._at(WorkflowState.FETCH_REMOTE); status=self._call("fetch_and_reconcile")
            self._at(WorkflowState.RECONCILE)
            if getattr(status,"relation",status) in {"ahead","diverged","unborn"}: raise SyncError("vault_not_reconciled","Vault must be synchronized before launch.",EXIT_CONFLICT)
            base=self._call("remote_oid")
            if not base: raise SyncError("remote_main_missing","Remote main is missing; run bootstrap first.",EXIT_CONFLICT)
            try:
                action=self._reconcile_three_way(base)
            finally:
                capture_destinations()
            self._at(WorkflowState.ACQUIRE_LOCK); lock=self._call("acquire",base); self.mutated=True; self.session=lock.session.session_id
            baseline=None
            if action=="apply":
                plan=self._call("prepare_remote_restore",base,self.session); self._at(WorkflowState.ARCHIVE_BEFORE_RESTORE); plan=self._call("archive_before_restore",plan); self._at(WorkflowState.APPLY_REMOTE_SAVE); self._call("apply_remote_save",plan)
                baseline=self._call("wait_save_stable"); self.baseline=baseline or self.baseline
            else:
                self._skip(WorkflowState.ARCHIVE_BEFORE_RESTORE); self._skip(WorkflowState.APPLY_REMOTE_SAVE)
            self._call("launch",lambda value:self._at(WorkflowState(value)))
            self._at(WorkflowState.WAIT_SAVE_STABLE)
            try: stable=self._call("wait_save_stable")
            except SyncError as original:
                try: quarantine_root=self._call("rescue_raw",None); capture_destinations()
                except Exception: raise SyncError("rescue_incomplete","Save stability failed and rescue archive could not be confirmed; run recover.",EXIT_RECOVERY_REQUIRED) from None
                raise
            self._at(WorkflowState.VALIDATE_SAVE)
            try: manifest=self._call("validate",stable,self.baseline or baseline)
            except SyncError:
                try:
                    quarantine_root=self._call("rescue_raw",stable); capture_destinations()
                except Exception:
                    raise SyncError("rescue_incomplete","Save validation failed and rescue archive could not be confirmed; run recover.",EXIT_RECOVERY_REQUIRED) from None
                raise
            self._at(WorkflowState.ARCHIVE_AFTER_GAME)
            archive_root=self._call("archive_after_game",manifest); capture_destinations()
            oid=self._call("snapshot",self.session,manifest,lambda value:self._at(WorkflowState(value))); safe_oid=oid; safe_root_hash=manifest["root_hash"]
            self._call("mark_committed",lock,oid,safe_root_hash)
            self._at(WorkflowState.PUSH,safe_oid=safe_oid,safe_root_hash=safe_root_hash); pushed=self._call("push",oid); safe_oid=pushed
            self._at(WorkflowState.RELEASE_LOCK)
            self._call("release",lock,pushed,manifest)
            self._at(WorkflowState.COMPLETE,safe_oid=pushed,safe_root_hash=(manifest or {}).get("root_hash")); return {"state":"COMPLETE","commit":pushed}
        except SyncError as error:
            capture_destinations()
            if self.mutated:
                # Preserve adapter-supplied diagnostic fields while giving every
                # post-lock failure the same recovery handoff contract.
                error.details = {**error.details, **recovery_details()}
            if error.code == "logging_failed": raise
            try: self.logger.write(self.state,"failed",error.code,session_id=self.session,last_successful_state=self.last_success,safe_oid=safe_oid,safe_root_hash=safe_root_hash,archive_root=archive_root,quarantine_root=quarantine_root,archive_id=archive_id,quarantine_id=quarantine_id)
            except Exception:
                # Before any mutation log failures are configuration; after it recovery is required.
                if lock is None: raise SyncError("logging_failed","Audit log could not be written before mutation.",2) from None
                raise SyncError("logging_failed","Audit log failed after a local mutation; run recover.",EXIT_RECOVERY_REQUIRED) from None
            raise
        except Exception:
            capture_destinations()
            try: self.logger.write(self.state,"failed","unexpected_failure",session_id=self.session,last_successful_state=self.last_success,safe_oid=safe_oid,safe_root_hash=safe_root_hash,archive_root=archive_root,quarantine_root=quarantine_root,archive_id=archive_id,quarantine_id=quarantine_id)
            except Exception: pass
            code = EXIT_RECOVERY_REQUIRED if self.mutated else 2
            error = SyncError("unexpected_failure","Launch workflow stopped; run recover before another launch.",code)
            if self.mutated: error.details = recovery_details()
            raise error from None
